extends: [eslint:recommended, prettier]
plugins: [prettier]
parser: typescript-eslint-parser
parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
env:
  es6: true
  browser: true
rules:
  prettier/prettier: [1, parser: typescript]
  max-len:
  - 1
  - tabWidth: 2
    ignoreUrls: true
    # Note: exclude all eslint- directives except for max-len itself since
    #       `// eslint-disable-line max-len` would cause this line to be
    #       ignored AND this rule to be disabled which would trigger
    #       --report-unused-disable-directives. By excluding max-len, the
    #       effect is to consider the line but disable this rule.
    ignorePattern: "^/// .+|// (?!eslint-.+max-len)eslint-.+"
  no-console: 1
  no-var: 1
  prefer-const: 1

  # This has overlap with TypeScript's noUnusedLocals and noUnusedParameters
  no-unused-vars: 0

  # Disable rules with known issues.
  # https://github.com/eslint/typescript-eslint-parser#known-issues
  no-undef: 0
